const engWords900 = [
  "going to",
  "the same",
  "seem to",
  "more than",
  "at least",
  "be to",
  "away from",
  "kind of",
  "at all",
  "as well",
  "be able",
  "like that",
  "in front",
  "for a moment",
  "why not",
  "sort of",
  "in front of",
  "this time",
  "used to",
  "a lot of",
  "be that",
  "this way",
  "all right",
  "that is what",
  "after all",
  "be afraid",
  "on it",
  "for long",
  "so much",
  "a bit",
  "it all",
  "no longer",
  "too much",
  "as soon as",
  "let's",
  "at once",
  "in fact",
  "the moment",
  "in my mind",
  "old man",
  "only one",
  "like this",
  "on the way",
  "how much",
  "be sorry",
  "at last",
  "feel like",
  "because of",
  "now that",
  "be supposed",
  "years ago",
  "all over",
  "at first",
  "this one",
  "be surprised",
  "so far",
  "that is why",
  "sound like",
  "make sure",
  "how many",
  "that is all",
  "as well as",
  "be about to",
  "had better",
  "how long",
  "do not care",
  "in the middle",
  "I am sorry",
  "along with",
  "by the time",
  "even more",
  "once more",
  "in the morning",
  "take care",
  "no matter",
  "as long as",
  "no doubt",
  "as far as",
  "in time",
  "or so",
  "on top",
  "ask for",
  "a week",
  "take care of",
  "be late",
  "nothing but",
  "all the time",
  "just like",
  "even though",
  "what about",
  "I am afraid",
  "in silence",
  "as to",
  "a day",
  "by now",
  "in on",
  "for the first time",
  "very much",
  "from where",
  "be sure",
  "search for",
  "find himself",
  "front door",
  "be worth",
  "on my own",
  "do not seem to",
  "one day",
  "take a breath",
  "a matter of",
  "last time",
  "some kind of",
  "from behind",
  "on earth",
  "it is time",
  "be used to",
  "back and forth",
  "one more",
  "would like",
  "one another",
  "seem like",
  "far away",
  "be lucky",
  "up and down",
  "take time",
  "be on one's way",
  "pay attention",
  "once again",
  "way out",
  "as for",
  "at the moment",
  "long ago",
  "show someone to",
  "for a long time",
  "to death",
  "I do not see",
  "by then",
  "same thing",
  "get married",
  "long enough",
  "for years",
  "why do not you",
  "in what",
  "from here",
  "at the time",
  "in early / early in",
  "next day",
  "feel about",
  "by the way",
  "half an hour",
  "in charge",
  "a great deal",
  "in the end",
  "some sort of",
  "in spite of",
  "every time",
  "more and more",
  "all day",
  "be proud",
  "too far",
  "ever since",
  "in only",
  "right away",
  "cell phone",
  "in a way",
  "for now",
  "next morning",
  "be up to",
  "a little more",
  "be good at",
  "get rid of",
  "shake hand",
  "no matter what",
  "in order to",
  "other than",
  "what the hell",
  "in the distance",
  "all of us",
  "be mad",
  "fall asleep",
  "how about",
  "for a minute",
  "all but",
  "after a while",
  "than ever",
  "for sure",
  "used to be",
  "whole thing",
  "far too",
  "parking lot",
  "be welcome",
  "should not be",
  "just about",
  "take place",
  "first thing",
  "old woman",
  "be aware of",
  "if anything",
  "it is about",
  "next time",
  "all the same",
  "have in mind",
  "thing to do",
  "here and there",
  "last year",
  "from there",
  "go to bed",
  "would you like",
  "sooner or later",
  "give way",
  "on board",
  "get ready",
  "thanks to",
  "from under",
  "it appears",
  "in a hurry",
  "for a long moment",
  "be interested in",
  "pretty much",
  "for an instant",
  "all along",
  "make a decision",
  "just now",
  "be proud of",
  "this evening",
  "turn away from",
  "under circumstances",
  "as it is",
  "at work",
  "do not you think",
  "find herself",
  "be different from",
  "get used to",
  "be in love",
  "of him",
  "for some reason",
  "the last thing",
  "go to sleep",
  "change mind",
  "more likely",
  "a long way",
  "be happy to",
  "and a half",
  "one and a half",
  "from time to time",
  "fall silent",
  "a good deal",
  "in the meantime",
  "come forward",
  "find myself",
  "at times",
  "in return",
  "I take it",
  "take a look",
  "for good",
  "work as",
  "in pain",
  "side by side",
  "around the corner",
  "as ever",
  "take a sip",
  "rest of us",
  "last week",
  "come to see",
  "be fond of",
  "close by",
  "not to mention",
  "put arm around",
  "clear of",
  "pretend to be",
  "thank God",
  "one or another",
  "on my mind",
  "good reason",
  "since then",
  "at hand",
  "fall in love",
  "catch breath",
  "smell like",
  "mind if",
  "this year",
  "never mind",
  "in less than",
  "all kinds",
  "the day before",
  "make up mind",
  "how come",
  "have dinner",
  "as a matter of fact",
  "from outside",
  "each time",
  "pretty well",
  "so far as",
  "and all",
  "next week",
  "push away",
  "have fun",
  "get to work",
  "from inside",
  "on foot",
  "next door",
  "in any way",
  "let alone",
  "for God's sake",
  "if you like",
  "be in the middle of",
  "from somewhere",
  "take a chance",
  "in the evening",
  "a long time ago",
  "in short",
  "be in love with",
  "out loud",
  "in the field",
  "so as",
  "in summer",
  "all things",
  "ask a question",
  "turn your back on",
  "son of a bitch",
  "the rest of my life",
  "take advantage of",
  "how is it",
  "hold breath",
  "right through",
  "in the light of",
  "in that case",
  "in truth",
  "with luck",
  "all of a sudden",
  "in this way",
  "get on with",
  "as of",
  "science fiction",
  "good luck",
  "under his breath",
  "in some way",
  "come running",
  "what good",
  "ever so",
  "in the name of something",
  "for about",
  "in other words",
  "from now on",
  "get in touch",
  "take hold of",
  "get worse",
  "be done with",
  "aside from",
  "feel sorry for",
  "in advance",
  "take a while",
  "in detail",
  "point of view",
  "get lost",
  "conference room",
  "later on",
  "as soon as possible",
  "make certain",
  "be designed to",
  "have lunch",
  "above all",
  "until now",
  "be certain of",
  "crime scene",
  "have to do with",
  "just the same",
  "different way",
  "at length",
  "solar system",
  "in a low voice",
  "they say",
  "in peace",
  "steering wheel",
  "from within",
  "all the more",
  "if you please",
  "be happy with",
  "what it is like",
  "best thing",
  "go along with",
  "on her own",
  "on time",
  "this kind of thing",
  "be engaged",
  "how old",
  "if necessary",
  "just like that",
  "at about",
  "feel that way",
  "face to face",
  "common sense",
  "over the top",
  "go crazy",
  "for as long as",
  "at best",
  "be in a hurry",
  "police station",
  "from the beginning",
  "sick of",
  "in a whisper",
  "at random",
  "of sorts",
  "come to life",
  "ground floor",
  "if I have to",
  "by the end",
  "be up against",
  "do my best",
  "find themselves",
  "for the time being",
  "I must say",
  "bad luck",
  "real estate",
  "go mad",
  "at all times",
  "index finger",
  "on purpose",
  "make a plan",
  "get angry",
  "you are welcome",
  "as is",
  "have breakfast",
  "for the most part",
  "do the right thing",
  "be angry with",
  "what with",
  "make a face",
  "from the start",
  "one more time",
  "get someone in trouble",
  "do business",
  "good sense",
  "make somebody sick",
  "this week",
  "so to speak",
  "from the outside",
  "good fortune",
  "just over",
  "waiting room",
  "make a deal",
  "in private",
  "make nervous",
  "far less",
  "of late",
  "prime minister",
  "one way or another",
  "all alone",
  "be happy about",
  "out of control",
  "by no means",
  "say goodbye",
  "that was it",
  "last name",
  "free from",
  "around the world",
  "hiding place",
  "in need of",
  "at the very least",
  "straight out",
  "take someone's word",
  "law enforcement",
  "have a drink",
  "black hole",
  "in a row",
  "from the inside",
  "get in the way",
  "stand guard",
  "push one's way",
  "sleeping bag",
  "pull together",
  "spend money",
  "keep warm",
  "give a hand",
  "about time",
  "the fact is",
  "full moon",
  "task force",
  "for real",
  "by yourself",
  "by far",
  "just a moment",
  "every now and then",
  "what that is",
  "once upon a time",
  "bus stop",
  "go all the way",
  "to and fro",
  "take part",
  "be in for",
  "all this stuff",
  "find yourself",
  "stay put",
  "as it were",
  "at someone's disposal",
  "if I were you",
  "be on fire",
  "make yourself comfortable",
  "to start with",
  "have a word",
  "every so often",
  "have done with",
  "by chance",
  "make friends",
  "in cash",
  "at will",
  "funny thing",
  "in these parts",
  "the worst thing",
  "leather jacket",
  "take risks",
  "empty of",
  "in half an hour",
  "none of your business",
  "go into details",
  "take a rest",
  "burst into tears",
  "make progress",
  "go nuts",
  "take a cab",
  "do a favor",
  "take a break",
  "make a noise",
  "get dressed",
  "to do someone a favour",
  "to do the cooking",
  "to do the housework",
  "to do the shopping",
  "to do the washing up",
  "to do your best",
  "to do your hair",
  "to have a good time",
  "to have a bath",
  "to have a drink",
  "to have a haircut",
  "to have a holiday",
  "to have a problem",
  "to have a relationship / to be in relationship",
  "to have lunch",
  "to have sympathy",
  "to break the law",
  "break a leg",
  "to break a promise",
  "to break a record",
  "to break someone’s heart",
  "to break the ice",
  "to break the news to someone",
  "to break the rules",
  "to take a break",
  "to take a chance",
  "to take a look",
  "to take a rest",
  "to take a seat",
  "to take a taxi",
  "to take an exam",
  "to take notes",
  "to take someone’s place",
  "to make a difference",
  "to make a mess",
  "to make a mistake",
  "to make a noise",
  "to make an effort",
  "to make money",
  "to make progress",
  "to make room",
  "to make trouble",
  "to catch the bus",
  "to catch a ball",
  "to catch a cold",
  "to catch a thief",
  "to catch fire",
  "to catch sight of",
  "to catch someone’s attention",
  "to catch someone’s eye",
  "to catch the flu",
  "to pay respect",
  "to pay a fine",
  "to pay attention",
  "to pay by credit card",
  "to pay cash",
  "to pay interest",
  "to pay someone a visit",
  "to pay the bill",
  "to pay the price",
  "to keep the change",
  "to keep a promise",
  "to keep a secret",
  "to keep an appointment",
  "to keep calm",
  "to keep in touch",
  "to keep quiet",
  "to keep someone’s place",
  "to save someone the trouble",
  "to save electricity",
  "to save energy",
  "to save money",
  "to save a seat for someone",
  "to save someone’s life",
  "to save something to a disk",
  "to save time",
  "to go bald",
  "to go abroad",
  "to go astray",
  "to go bad",
  "to go bankrupt",
  "to go blind",
  "to go crazy",
  "to go fishing",
  "to go mad",
  "to go missing",
  "to go online",
  "to go out of business",
  "to go overseas",
  "to go quiet",
  "to go sailing",
  "to go to war",
  "to come under attack",
  "to come close",
  "to come direct",
  "come early",
  "to come first",
  "to come into view",
  "to come last",
  "to come late",
  "to come on time",
  "to come prepared",
  "to come right back",
  "to come to a decision",
  "to accuse (someone) of ([doing] something)",
  "Please don’t accuse me of forgetting to lock the door.",
  "to add (something) to (something else)",
  "Shall I add your name to the list?",
  "to admire (someone) for ([doing] something)",
  "I don’t agree with her, but I admire her for sticking to her principles.",
  "to agree on (topic)",
  "Governments will be invited to agree on the necessary future actions.",
  "to agree with (someone)",
  "I don’t agree with this answer.",
  "to apologize to (someone) for ([doing] something)",
  "We apologize to our clients for the late departure of this flight",
  "to approve of (something)",
  "My parents have never approved of any of my girlfriends.",
  "to argue with (someone) about (topic)",
  "I have been arguing with my brother about this for years.",
  "to arrive at (a building, room, site, event)",
  "We arrived at the art gallery just as it was closing.",
  "to arrive in (a city, country)",
  "Immigrants who arrived in the country after 2005 have to take a special language test.",
  "to ask (someone) about (someone/topic)",
  "Let’s ask the travel agent about flights to Europe.",
  "to ask (someone) for (something)",
  "My son asked for a video game for Christmas.",
  "to believe in (something)",
  "I’m beginning to think you actually believe in ghosts!",
  "to belong to (someone)",
  "The car belongs to the woman next door.",
  "to blame (someone) for ([doing] something)",
  "She doesn’t blame anyone for her father’s death.",
  "to borrow (something) from (someone)",
  "I borrowed my ideas from Eliot’s famous poem ‘The Waste Land’.",
  "to care about (someone/something)",
  "All you care about is your precious collection.",
  "to compare (something) to/with (something else)",
  "It is difficult to compare our results to/with studies conducted in the United States.",
  "to complain to (someone) about (something)",
  "She often complains to her friends about not feeling appreciated at work.",
  "to concentrate on ([doing] something)",
  "Let’s try to concentrate our efforts on finishing this job today.",
  "to consist of (some things)",
  "The team consists of four Europeans and two Americans.",
  "to consent to ([doing] something)",
  "I will not consent to your marriage.",
  "to cover (something) with (something else)",
  "The floor is covered with the expensive carpet.",
  "to discuss (something) with (someone)",
  "We need to discuss compensation with the boss.",
  "to dream about/of (someone/something)",
  "I dream of/about one day working for myself and not having a boss.",
  "to escape from (somewhere)",
  "His attempt to escape from jail was successful.",
  "to explain (topic) to (someone)",
  "Can you explain the route to me?",
  "to excuse (someone) for ([doing] something)",
  "I hope you’ll excuse me for being so late.",
  "to forgive (someone) for ([doing] something)",
  "She eventually forgave him for forgetting her birthday.",
  "to graduate from (a place)",
  "After he graduated from high school, he joined the Army.",
  "to happen to (someone)",
  "This is the best thing that’s ever happened to me.",
  "to help (someone) with (something)",
  "I will help you with cooking.",
  "to hide (something) from (someone)",
  "I wanted to hide his present from him until his birthday.",
  "to participate in (something)",
  "She never participates in any of our discussions, does she?",
  "to pay (price) for (something)",
  "We all pay for our mistakes in some way at some time.",
  "to plan on ([doing] something)",
  "We were planning on just having a snack and catching the early train.",
  "to pray for (someone/something)",
  "The only thing you can do now is to pray for others.",
  "to prefer (something) to (something else)",
  "I prefer tea to coffee.",
  "to prohibit (someone) from ([doing] something)",
  "The committee voted to prohibit people from leaving before the meeting was over.",
  "to protect (someone) from (something)",
  "She’ll do anything to protect her children from harm.",
  "to provide (someone) with (something)",
  "The search provided the police with several vital clues.",
  "to recover from (something)",
  "I hope I recover from this cough soon.",
  "to remind (someone) of (something)",
  "This song reminds me of our trip to Spain.",
  "to rescue (someone) from (something)",
  "He rescued a child from drowning.",
  "to respond to (someone/something)",
  "The police responded right away to the riot call.",
  "to save (someone) from (something)",
  "Only hard work will save this company from bankruptcy.",
  "to separate (something) from (something else)",
  "The nurse separated the infected people from the healthy ones.",
  "to scold (someone) for ([doing] something)",
  "The manager scolded the worker for misplacing the door key.",
  "to smile at (someone) for ([doing] something)",
  "He smiled at her for being so cute.",
  "to speak to/with (someone) about (topic)",
  "I should speak to/with my mother about this issue.",
  "to stare at (something/someone)",
  "Why are you staring at me?",
  "to stop (someone) from ([doing] something)",
  "I can’t stop her from running away.",
  "to substitute (something) for (something else/someone)",
  "Please substitute fish for beef on my dinner order.",
  "to succeed in ([doing] something)",
  "I hope you succeed in your new job.",
  "to take advantage of (someone/something/situation)",
  "We took advantage of the beautiful weather and went to the beach.",
  "to take care of (something/someone)",
  "Please take care of my child while I’m away.",
  "to talk to/with (someone) about (topic)",
  "Can I talk to/with you for a minute about last night?",
  "to travel to (somewhere)",
  "She is old enough to travel to other countries alone.",
  "to vote for (someone)",
  "I voted for Donald Trump last year.",
  "to wish for (something)",
  "She spent most of her life wishing for Prince Charming, who would come along and sweep her off her feet.",
  "addiction to (someone/something)",
  "His addiction to surfing the Internet is a problem.",
  "advantage of (something)",
  "He has the advantage of speaking English fluently.",
  "anxiety about (something)",
  "Her anxiety about speaking in public caused her to lose the job.",
  "belief in (someone/something)",
  "His belief in not harming animals was something he learned from his mother.",
  "dedication to (something)",
  "His dedication to teaching was impressive.",
  "demand for (something)",
  "The government is unlikely to agree to the rebels’ demands for independence.",
  "experience in (something)",
  "She has a great deal of experience in introducing new products to international markets.",
  "fear of (someone/something)",
  "His fear of flying made travel difficult.",
  "habit of ([doing] something)",
  "His habit of smoking in restaurants caused many problems in California.",
  "interest in (someone/something)",
  "Her career as a pilot evolved out of her interest in flying.",
  "love of (someone/[doing] something)",
  "His love of singing developed when he was a child.",
  "memory of (someone/something)",
  "Their memories of traveling in Africa will stay with them forever.",
  "process of ([doing] something)",
  "The process of painting such a large mural is more complicated than you might think.",
  "reaction to (something)",
  "His reaction to winning the prize was quite funny.",
  "reason for (something)",
  "The main reason for taking the course is to improve your language skills.",
  "regret for (something)",
  "The criminal’s regret for committing the crime did not convince the judge.",
  "responsibility for ([doing] something)",
  "His responsibility for completing the project on time was acknowledged by the company.",
  "story about (something)",
  "I don’t know if I believe his story about seeing a UFO.",
  "lack of (something)",
  "His answer demonstrated a complete lack of understanding of the question.",
  "reply to (someone/something)",
  "There were very few replies to our advertisement.",
  "solution to (something)",
  "I need to find a solution to this problem.",
  "tax on (something)",
  "They’re putting up the tax on cigarettes.",
  "trouble with (someone/something)",
  "She’s been having a lot of trouble with her boss recently.",
  "cause of (something)",
  "The police are still trying to establish the cause of the fire.",
  "alternative to (something)",
  "After the public protests the government had no alternative but to change its policy.",
  "example of (something)",
  "This is a good example of medieval Chinese architecture.",
  "accustomed to (something/ doing something)",
  "I am not accustomed to being interrupted.",
  "accused of (something/ doing something)",
  "I don’t want to be accused of stealing.",
  "allergic to (something)",
  "He is highly allergic to penicillin.",
  "amazed at/by (something)",
  "She was amazed at how calm she felt after the accident.",
  "anxious about (something)",
  "He seemed anxious about the meeting.",
  "ashamed of (someone)",
  "I could tell they were ashamed of me",
  "angry with (someone)",
  "I can’t be angry with them for that.",
  "attached to (something/someone)",
  "John is really attached to his old-fashioned ideas.",
  "bad at (doing something)",
  "I’m bad at the whole dating thing, man.",
  "based on (something)",
  "The plot is based on a true story.",
  "brilliant at (something)",
  "My father was brilliant at making speeches.",
  "busy with ([doing] something)",
  "You’re always busy with your study group.",
  "capable of ([doing] something)",
  "Only the Democratic Party is capable of running the country.",
  "clever at ([doing] something)",
  "He was very clever at getting what he wanted",
  "connected with (something/someone)",
  "The bathroom is connected with the bedroom.",
  "crazy about (something/someone)",
  "Both my sons are crazy about football.",
  "curious about (something/someone)",
  "I was curious about how you’ve been.",
  "different from (something/someone)",
  "This part is totally different from anything else that he’s done.",
  "disappointed with (something/someone)",
  "I was very disappointed with myself.",
  "eligible for (something)",
  "Are you eligible for early retirement?",
  "excited about (something)",
  "I am very excited about our trip.",
  "faithful to (someone)",
  "He was faithful to his wife throughout their 30-year marriage.",
  "familiar with (someone or something)",
  "Are you familiar with changing a flat tire?",
  "frightened of (someone/something)",
  "Are you frightened of spiders?",
  "furious about (someone/something)",
  "He’s furious about the way he’s been treated.",
  "gentle with (someone)",
  "He’s very gentle with his kids.",
  "identical with/to (someone/something)",
  "The tests are identical to those carried out last year.",
  "impressed with (someone/something)",
  "He tried to impress me with his extensive knowledge of wine.",
  "innocent of (something)",
  "He firmly believes that she is innocent of the crime.",
  "interested in (someone/something)",
  "She’s at that age where she’s starting to get interested in boys.",
  "incapable of ([doing] something)",
  "He seems incapable of walking past a music shop without going in and buying another CD.",
  "kind to (someone)",
  "Please be kind to your sister!",
  "lucky at (something)",
  "That’s why I’m so lucky at cards and love.",
  "polite to (someone)",
  "I’m afraid I wasn’t very polite to her.",
  "proud of (something/someone)",
  "She was so proud of her son.",
  "punished for (something)",
  "They must be severely punished for these crimes.",
  "puzzled by/about (something)",
  "Critics remain puzzled by/about the British election results",
  "ready for (something)",
  "The army was ready for action.",
  "responsible for (something/someone)",
  "The city council is responsible for keeping the streets clean.",
  "sad about (something/someone)",
  "I felt terribly sad about it.",
  "satisfied with (something/someone)",
  "Are you satisfied with the new arrangement?",
  "sick of (something/someone)",
  "I’m sick of the way you’re behaving.",
  "shocked by (something/someone)",
  "I still remember how deeply I was shocked by them.",
  "successful in (something)",
  "I think that the best way to be successful in life is to do what you’re passionate about.",
  "sure about (something/someone)",
  "Is there anything you’re not sure about?",
  "surprised at (something/someone)",
  "We were very surprised at the result.",
  "terrified of (something/someone)",
  "I’m terrified of the dark.",
  "tired of (something/someone)",
  "I’m so tired of doing the same job, day after day.",
  "upset about (something/someone)",
  "Don’t get upset about the dress – there’s only a little stain on it."
]
